; It works! It's fucking working! Muahaha

(set_font "display.mf")

(= on_init
    (fn ()
        (print "The shell says hello world!")

        (let i 0)
        (let y 15)
        (while (< i 6)
            (let s (* i 6))
            (write "MISFITS" 0 y 8 s ALIGN_CENTER)
            (= i (+ i 1))
            (= y (+ y s 2))
        )
    )
)

(= on_minute
    (fn (time)
        (clear false)

        (write "MISFITS" 10 10 8 8 ALIGN_LEFT  (- SCR_WIDTH 20))
        (write "TUE" 10 10 8 8 ALIGN_RIGHT (- SCR_WIDTH 20))

        (rect_line true 154 7 37 14)

        (write "00 00" 0 80 16 32 ALIGN_CENTER)
    )
)

(= on_button
    (fn (btn)
        (clear false)

        (if
            (is btn 0) (write "ZERO" 0 80 8 8 ALIGN_CENTER)
            (is btn 1) (write "ONE" 0 80 8 8 ALIGN_CENTER)
            (is btn 2) (write "TWO" 0 80 8 8 ALIGN_CENTER)
            (is btn 3) (write "THREE" 0 80 8 8 ALIGN_CENTER)
        )
    )
)
